services:
  redis:
    image: redis
    # container_name: redis
    restart: always
    ports:
      - '6379:6379'

  app:
    build: . # This tells Docker Compose to use the Dockerfile in the current directory
    # container_name: nestjs-app
    depends_on:
      - redis
    environment:
      REDIS_HOST: redis
      REDIS_PORT: 6379
    ports:
      - '3000:3000'
    # networks:
    #   - app-network
# networks:
#   app-network:
#     driver: bridge
